//
//  ClingMacroBridge.h
//  ClingSDK
//
//  Created by zhusanbao on 2025/3/27.
//  Copyright © 2025 Roffa. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "ClingBLEModel.h"


typedef NS_ENUM(NSUInteger, SCREEN_DISPLAY_OPTION) {
    step = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_STEP,
    distance = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_DISTANCE,
    calories = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_CALORIES,
    activeTime = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_ACTIVE_TIME,
    heartRate = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_HEART_RATE,
    weather = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_WEATHER,
    pm2p5 = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_PM2P5,
    
    startRunning = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_START_RUNNING,
    analysis = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_ANALYSIS,
    skinTemp = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_SKIN_TEMP,
    uv = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_UV,
    bloodPressure = PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_BLOODPRESSURE,
    
    defaultValue = (PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_STEP | PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_HEART_RATE | PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_START_RUNNING | PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_SKIN_TEMP | PERIPHERAL_PROFILE_SCREEN_DISPLAY_OPTION_UV)
};

